//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTauWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BOOK_VE_TAUEntities : DbContext
    {
        public BOOK_VE_TAUEntities()
            : base("name=BOOK_VE_TAUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DM_CONG_TY> DM_CONG_TY { get; set; }
        public DbSet<GD_BOOKING_FROM_WEB> GD_BOOKING_FROM_WEB { get; set; }
    }
}
