//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTauWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CONG_TY
    {
        public int ID { get; set; }
        public string TEN_CONG_TY { get; set; }
        public string DIA_CHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
    }
}
