//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTauWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_BOOKING_FROM_WEB
    {
        public int ID { get; set; }
        public string TEN_CONG_TY { get; set; }
        public Nullable<int> SO_VE { get; set; }
        public Nullable<int> ID_CHIEU { get; set; }
        public Nullable<System.DateTime> NGAY_DI { get; set; }
        public Nullable<System.DateTime> NGAY_DAT { get; set; }
        public Nullable<int> SO_VE_VIP { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
        public string GHI_CHU_TIEP_NHAN { get; set; }
        public string SDT { get; set; }
    }
}
