//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTau
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookVeEntities : DbContext
    {
        public BookVeEntities()
            : base("name=BookVeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CM_DM_TU_DIEN> CM_DM_TU_DIEN { get; set; }
        public DbSet<DM_LOAI_TU_DIEN> DM_LOAI_TU_DIEN { get; set; }
        public DbSet<GD_BOOK_VE> GD_BOOK_VE { get; set; }
        public DbSet<GD_BOOK_VE_DETAIL> GD_BOOK_VE_DETAIL { get; set; }
        public DbSet<V_SO_DO_TAU> V_SO_DO_TAU { get; set; }
    }
}
