//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTau
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BookVeEntities : DbContext
    {
        public BookVeEntities()
            : base("name=BookVeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CM_DM_TU_DIEN> CM_DM_TU_DIEN { get; set; }
        public DbSet<DM_LOAI_TU_DIEN> DM_LOAI_TU_DIEN { get; set; }
        public DbSet<GD_BOOK_VE> GD_BOOK_VE { get; set; }
        public DbSet<GD_BOOK_VE_DETAIL> GD_BOOK_VE_DETAIL { get; set; }
        public DbSet<V_SO_DO_TAU> V_SO_DO_TAU { get; set; }
    
        public virtual ObjectResult<GET_THONG_KE_VE_Result> GET_THONG_KE_VE(string thang, string nam, Nullable<int> chieu)
        {
            var thangParameter = thang != null ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(string));
    
            var namParameter = nam != null ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(string));
    
            var chieuParameter = chieu.HasValue ?
                new ObjectParameter("chieu", chieu) :
                new ObjectParameter("chieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_THONG_KE_VE_Result>("GET_THONG_KE_VE", thangParameter, namParameter, chieuParameter);
        }
    
        public virtual ObjectResult<getSoDoTau_Result> getSoDoTau(Nullable<System.DateTime> ngay, Nullable<decimal> idToa)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("ngay", ngay) :
                new ObjectParameter("ngay", typeof(System.DateTime));
    
            var idToaParameter = idToa.HasValue ?
                new ObjectParameter("idToa", idToa) :
                new ObjectParameter("idToa", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSoDoTau_Result>("getSoDoTau", ngayParameter, idToaParameter);
        }
    
        public virtual ObjectResult<getDsCongTy_Result> getDsCongTy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDsCongTy_Result>("getDsCongTy");
        }
    
        public virtual ObjectResult<get_cong_no_Result> get_cong_no(Nullable<System.DateTime> ngay_bat_dau, Nullable<System.DateTime> ngay_ket_thuc, Nullable<int> num_cong_ty, string ten_cong_ty)
        {
            var ngay_bat_dauParameter = ngay_bat_dau.HasValue ?
                new ObjectParameter("ngay_bat_dau", ngay_bat_dau) :
                new ObjectParameter("ngay_bat_dau", typeof(System.DateTime));
    
            var ngay_ket_thucParameter = ngay_ket_thuc.HasValue ?
                new ObjectParameter("ngay_ket_thuc", ngay_ket_thuc) :
                new ObjectParameter("ngay_ket_thuc", typeof(System.DateTime));
    
            var num_cong_tyParameter = num_cong_ty.HasValue ?
                new ObjectParameter("num_cong_ty", num_cong_ty) :
                new ObjectParameter("num_cong_ty", typeof(int));
    
            var ten_cong_tyParameter = ten_cong_ty != null ?
                new ObjectParameter("ten_cong_ty", ten_cong_ty) :
                new ObjectParameter("ten_cong_ty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_cong_no_Result>("get_cong_no", ngay_bat_dauParameter, ngay_ket_thucParameter, num_cong_tyParameter, ten_cong_tyParameter);
        }
    
        public virtual int Pr_delete_all_gd_book_ve(Nullable<decimal> iD_GD_BOOK_VE)
        {
            var iD_GD_BOOK_VEParameter = iD_GD_BOOK_VE.HasValue ?
                new ObjectParameter("ID_GD_BOOK_VE", iD_GD_BOOK_VE) :
                new ObjectParameter("ID_GD_BOOK_VE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_delete_all_gd_book_ve", iD_GD_BOOK_VEParameter);
        }
    
        public virtual int Pr_delete_records_cua_gd_book_ve(Nullable<decimal> iD_GD_BOOK_VE)
        {
            var iD_GD_BOOK_VEParameter = iD_GD_BOOK_VE.HasValue ?
                new ObjectParameter("ID_GD_BOOK_VE", iD_GD_BOOK_VE) :
                new ObjectParameter("ID_GD_BOOK_VE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_delete_records_cua_gd_book_ve", iD_GD_BOOK_VEParameter);
        }
    }
}
