//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTau
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_DM_TU_DIEN
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_LOAI_TU_DIEN { get; set; }
        public string MA_TU_DIEN { get; set; }
        public string TEN_TU_DIEN { get; set; }
    }
}
