//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTau
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_BOOK_VE_DETAIL
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_GD_BOOK_VE { get; set; }
        public Nullable<decimal> ID_TOA { get; set; }
        public Nullable<decimal> GHE_SO { get; set; }
    }
}
