//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTau
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_BOOK_VE
    {
        public decimal ID { get; set; }
        public string TEN_CONG_TY { get; set; }
        public Nullable<decimal> SO_VE { get; set; }
        public Nullable<decimal> ID_CHIEU { get; set; }
        public Nullable<decimal> GIA_VE { get; set; }
        public Nullable<System.DateTime> NGAY_DI { get; set; }
        public Nullable<System.DateTime> NGAY_VE { get; set; }
        public Nullable<decimal> ID_TAI_KHOAN { get; set; }
        public string MA_PHIEU_THU { get; set; }
        public string CAP_CHO_YN { get; set; }
        public string VIP_YN { get; set; }
        public Nullable<System.DateTime> NGAY_DAT { get; set; }
        public string EMAIL { get; set; }
        public string GHI_CHU { get; set; }
    }
}
