//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookVeTau
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SO_DO_TAU
    {
        public Nullable<decimal> GHE_SO { get; set; }
        public string TEN_CONG_TY { get; set; }
        public string CAP_CHO { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> ID_TOA { get; set; }
        public Nullable<System.DateTime> NGAY_DAT { get; set; }
        public Nullable<System.DateTime> NGAY_DI { get; set; }
        public Nullable<System.DateTime> NGAY_VE { get; set; }
        public Nullable<decimal> ID_CHIEU { get; set; }
    }
}
